name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Echo World"]
    types:
      - completed
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  run_on_merge:
    if: |
      github.event.workflow_run.conclusion == 'success' && 
      github.event.pull_request.merged == true && 
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    
    steps:
      - name: Execute Post-Merge Actions
        run: echo "Previous workflow completed and PR merged to main!"
        