name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Echo World"]
    types:
      - completed

jobs:
  run_on_merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main  # Ensure we're on the latest main branch

      - name: Check if last commit was a merge
        run: |
          LAST_COMMIT_MSG=$(git log -1 --pretty=%B)
          if echo "$LAST_COMMIT_MSG" | grep -qi "merge pull request"; then
            echo "This was a merge commit!"
          else
            echo "No merge detected, exiting."
            exit 1
          fi

      - name: Echo Dependent Workflow
        run: echo "First workflow completed, and a merge happened into main!"
