name: Dependent Workflow

on:
  pull_request:
    types:
      - closed

  workflow_run:
    workflows: ["Echo World"]
    types:
      - completed

jobs:
  check_conditions:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check PR Merge & Workflow Completion
        id: check
        run: |
          PR_MERGED=false
          WORKFLOW_SUCCESS=false

          if [[ "${{ github.event_name }}" == "pull_request" && "${{ github.event.pull_request.merged }}" == "true" && "${{ github.event.pull_request.base.ref }}" == "main" ]]; then
            PR_MERGED=true
          fi

          if [[ "${{ github.event_name }}" == "workflow_run" && "${{ github.event.workflow_run.conclusion }}" == "success" ]]; then
            WORKFLOW_SUCCESS=true
          fi

          if [[ "$PR_MERGED" == "true" && "$WORKFLOW_SUCCESS" == "true" ]]; then
            echo "should_run=true" >> $GITHUB_OUTPUT
          else
            echo "should_run=false" >> $GITHUB_OUTPUT

  run_on_merge:
    needs: check_conditions
    if: needs.check_conditions.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Dependent Workflow
        run: echo "First workflow completed, and a PR was merged into main!"
