name: Dependent Workflow

on:
  workflow_run:
    workflows: ["Echo World"]
    types:
      - completed

  push:
    branches:
      - main

jobs:
  check_conditions:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check.outputs.should_run }}
    steps:
      - name: Check Push & Workflow Completion
        id: check
        run: |
          PUSH_TO_MAIN="false"
          WORKFLOW_SUCCESS="false"

          if [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
            PUSH_TO_MAIN="true"
          fi

          if [ "${{ github.event_name }}" = "workflow_run" ] && [ "${{ github.event.workflow_run.conclusion }}" = "success" ]; then
            WORKFLOW_SUCCESS="true"
          fi

          if [ "$PUSH_TO_MAIN" = "true" ] && [ "$WORKFLOW_SUCCESS" = "true" ]; then
            echo "should_run=true" >> "$GITHUB_OUTPUT"
          else
            echo "should_run=false" >> "$GITHUB_OUTPUT"

  run_on_push:
    needs: check_conditions
    if: needs.check_conditions.outputs.should_run == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Dependent Workflow
        run: echo "First workflow completed, and a push happened to main!"
