name: Dependent Workflow

on:
  pull_request:
    types:
      - closed # Triggers when a PR is closed

  workflow_run:
    workflows: ["Echo World"]
    types:
      - completed

jobs:
  run_on_merge:
    if: |
      github.event.pull_request.merged == true &&
      github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Dependent Workflow
        run: echo "First workflow completed, and a merge happened into main!"
#####